export const FETCH_FLIGHTS = 'FLIGHTS/FETCH_FLIGHTS'
export const REQUESTED_FLIGHTS = 'FLIGHTS/REQUESTED_FLIGHTS'
export const REQUESTED_FLIGHTS_SUCCESS = 'FLIGHTS/REQUESTED_FLIGHTS_SUCCESS'
export const REQUESTED_FLIGHTS_FALIURE = 'FLIGHTS/REQUESTED_FLIGHTS_FALIURE'

export const ADD_FLIGHT_TO_FAVOURITES = 'FLIGHTS/ADD_FLIGHT_TO_FAVOURITES'
export const REMOVE_FLIGHT_FROM_FAVOURITES = 'FLIGHTS/REMOVE_FLIGHT_FROM_FAVOURITES'
